name: "PR"

on:
  push:

env:
  WORKING_DIRECTORY: src
  DOCKERFILE_PATH: DockerWorkerService/Dockerfile
  ACR_REGISTRY: likvido
  AKS_CLUSTER_NAME: tests
  APP_NAME: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Store image name
        run: echo "::set-env name=IMAGE_NAME::${{ env.ACR_REGISTRY }}.azurecr.io/${{ env.APP_NAME }}_${{ env.AKS_CLUSTER_NAME }}:${{ github.run_number }}"
      - name: Checkout source
        uses: actions/checkout@v2
      - name: EXECUTE
        uses: boychenko/actions/pr@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
        env: 
          AZURE_SERVICE_PRINCIPAL_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
          AZURE_SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }}
