name: "PR"

on:
  push:

env:
  WORKING_DIRECTORY: src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: EXECUTE
        uses: boychenko/actions/pr@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}