name: "Env tests"

on:
  push:
    branches:
      - "master"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.5.0
        with:
            dotnet-version: '3.1.x'
      - name: Test
        run: dotnet test --logger:trx
        working-directory: src/App1.Tests/
