name: "Test results"

on:
  push:
    branches:
      - "master"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.5.0
        with:
            dotnet-version: '3.1.x'
      - name: Test
        run: dotnet test --logger:nunit
        working-directory: src/App1.Tests/

      - uses: boychenko/nunit-reporter@build
        if: always()
        with:
          path: src/App1.Tests/TestResults/*.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish Test Report
      #   if: always()
      #   uses: scacap/action-surefire-report@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     report_paths: src/App1.Tests/TestResults/*.xml
      # - uses: MirrorNG/nunit-reporter@v1.0.9
      #   if: always()
      #   with:
      #     path: src/App1.Tests/TestResults/*.xml
      #     access-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Test
      #   run: dotnet test --logger:xunit
      #   working-directory: src/App1.Tests/
      # - name: XUnit Viewer
      #   id: xunit-viewer
      #   if: ${{ always() }}
      #   uses: AutoModality/action-xunit-viewer@v1  
      #   with:
      #     results: src/App1.Tests/TestResults/
      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v2
      #   if: ${{ always() }}
      #   with:
      #     name: ${{ steps.xunit-viewer.outputs.report-name }}
      #     path: ${{ steps.xunit-viewer.outputs.report-dir }}

