name: "Env tests"

on:
  push:
    branches:
      - "master"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.5.0
        with:
            dotnet-version: '3.1.x'
      - name: Test
        run: dotnet test --logger:trx
        working-directory: src/App1.Tests/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-results.trx
          path: src/App1.Tests/TestResults/*.trx

